"""
Phase 7 — Common Specialized Science Models and Interfaces.
Defines unified evidence representations, identification statuses, confidence models,
and storage repository protocols for eDNA, otolith image, and taxonomy workflows.
"""

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Protocol, Union

from data_pipeline.shared.models import DomainType


class TaxonResolverProtocol(Protocol):
    """
    Protocol for resolving candidate scientific/common taxon names.
    Enables taxonomy resolution dependency injection across eDNA and Otolith services.
    """
    def resolve_taxon(self, candidate_name: str) -> Any:
        ...


class EvidenceType(str, Enum):
    """Categories of scientific evidence generated by specialized modules."""
    EDNA_SEQUENCE = "edna_sequence"
    OTOLITH_IMAGE = "otolith_image"
    TAXONOMIC_RECORD = "taxonomic_record"
    MORPHOMETRIC = "morphometric"
    BIOCHEMICAL = "biochemical"
    UNKNOWN = "unknown"


class IdentificationStatus(str, Enum):
    """Confidence and verification status of a scientific detection/identification."""
    CONFIRMED = "confirmed"          # High confidence match against validated reference
    PROVISIONAL = "provisional"      # Moderate confidence or heuristic candidate
    UNRESOLVED = "unresolved"        # No match or below confidence threshold
    FLAGGED = "flagged"              # Ambiguous (multiple conflicting candidates) or low quality
    REJECTED = "rejected"            # Input data invalid or corrupted


class ConfidenceLevel(str, Enum):
    """Categorical confidence rating for human-readable scientific reporting."""
    HIGH = "high"                    # >= 0.90
    MEDIUM = "medium"                # 0.70 - 0.89
    LOW = "low"                      # < 0.70
    UNKNOWN = "unknown"              # Unresolved or non-applicable


@dataclass
class ScientificEvidence:
    """
    Structured container for raw scientific observations, extracted features,
    and computational metrics used to substantiate an identification.
    """
    evidence_id: str
    evidence_type: EvidenceType
    source_identifier: Optional[str] = None
    features: Dict[str, Any] = field(default_factory=dict)
    metrics: Dict[str, float] = field(default_factory=dict)
    raw_reference: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    provenance: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        res = asdict(self)
        res["evidence_type"] = self.evidence_type.value if hasattr(self.evidence_type, "value") else str(self.evidence_type)
        return res


@dataclass
class SpecializedResult:
    """
    Standardized result contract returned across all Phase 7 scientific workflows.
    Explicitly distinguishes evidence generation from identification and confidence.
    """
    result_id: str
    domain: str
    target_entity: Optional[str] = None          # Detected scientific name, taxon, or class
    common_name: Optional[str] = None
    status: IdentificationStatus = IdentificationStatus.PROVISIONAL
    confidence_score: Optional[float] = None     # Numeric score [0.0, 1.0]
    confidence_level: ConfidenceLevel = ConfidenceLevel.UNKNOWN
    confidence_method: str = "deterministic_baseline" # e.g. 'deterministic_kmer', 'heuristic_morphological', 'cnn_v1'
    is_ml_prediction: bool = False               # False for Phase 7 baselines, True when Phase 8 models are active
    evidence: Optional[ScientificEvidence] = None
    alternative_candidates: List[Dict[str, Any]] = field(default_factory=list)
    taxonomic_hierarchy: Optional[Dict[str, str]] = None
    provenance: Dict[str, Any] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        res = asdict(self)
        res["status"] = self.status.value if hasattr(self.status, "value") else str(self.status)
        res["confidence_level"] = self.confidence_level.value if hasattr(self.confidence_level, "value") else str(self.confidence_level)
        if self.evidence:
            res["evidence"] = self.evidence.to_dict()
        return res


class StorageRepository(Protocol):
    """
    Abstract storage boundary for persisting scientific evidence and results.
    Enables Phase 8 or backend services to attach database/cloud persistence cleanly.
    """
    def save_evidence(self, evidence: ScientificEvidence) -> str:
        ...

    def get_evidence(self, evidence_id: str) -> Optional[ScientificEvidence]:
        ...

    def save_result(self, result: SpecializedResult) -> str:
        ...

    def get_result(self, result_id: str) -> Optional[SpecializedResult]:
        ...


class InMemoryStorageRepository:
    """Default in-memory repository implementation for test fixtures and standalone operation."""
    def __init__(self) -> None:
        self.evidence_store: Dict[str, ScientificEvidence] = {}
        self.result_store: Dict[str, SpecializedResult] = {}

    def save_evidence(self, evidence: ScientificEvidence) -> str:
        self.evidence_store[evidence.evidence_id] = evidence
        return evidence.evidence_id

    def get_evidence(self, evidence_id: str) -> Optional[ScientificEvidence]:
        return self.evidence_store.get(evidence_id)

    def save_result(self, result: SpecializedResult) -> str:
        self.result_store[result.result_id] = result
        return result.result_id

    def get_result(self, result_id: str) -> Optional[SpecializedResult]:
        return self.result_store.get(result_id)
